name: dependencies
description: A simple and modular dependency injection system without using reflection.
version: 0.1.5
homepage: https://github.com/marcguilera/dependencies.dart
author: marcguilera <marcguilerap@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  quiver: ^2.0.1
  disposables: ^0.1.2

dev_dependencies:
  test: ^1.0.0
