name: event_bus
version: 1.1.1
author: Marco Jakob <majakob@gmx.ch>
description: A simple Event Bus using Dart Streams for decoupling applications
repository: https://github.com/marcojakob/dart-event-bus
homepage: https://code.makery.ch/library/dart-event-bus/
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  build_runner: ^1.2.5
  build_web_compilers: ^1.1.0
  build_test: ^0.10.3
  logging: ^0.11.0
  test: ^1.5.0
