name: gradient_widgets
description: A minimal set of Flutter widgets encased with beautiful gradients.
version: 0.5.2
homepage: https://github.com/bluemix/gradient-widgets

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

