include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    prefer_single_quotes: ignore
    todo: ignore
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - avoid_catches_without_on_clauses
    - avoid_positional_boolean_parameters
    - avoid_renaming_method_parameters
    - avoid_unused_constructor_parameters
    - control_flow_in_finally
    - directives_ordering
    - lines_longer_than_80_chars
    - package_api_docs
    - prefer_asserts_in_initializer_lists
    - prefer_if_elements_to_conditional_expressions
    - prefer_inlined_adds
    - provide_deprecation_message
    - unnecessary_parenthesis
