name: timezone
version: 0.5.7
authors:
- Boris Kaul <localvoid@gmail.com>
- Sam Rawlins <sam.rawlins@gmail.com>
description: Time zone database and time zone aware DateTime.
homepage: https://github.com/srawlins/timezone
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  path: '^1.3.0'
dev_dependencies:
  args: any
  glob: any
  logging: any
  pedantic: ^1.9.0
  test: ^1.10.0
