name: flutter_staggered_grid_view
description: A Flutter staggered grid view
version: 0.2.7
author: Romain Rastel <lets4r@gmail.com>
homepage: https://github.com/letsar/flutter_staggered_grid_view
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.3.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=1.19.0 <3.0.0"
