name: asn1lib
version: 0.6.5
authors:
- Warren Strange <warren.strange@gmail.com>
- Steven Roose <stevenroose@gmail.com>
- Jonas Kello <jonas.kello@gmail.com>
- David Janes <davidjanes@davidjanes.com>
- Daniel Linsenmeier <daniel@ephenodrom.de>
description: An ASN1 parser library for Dart. Encodes / decodes from ASN1 Objects to BER bytes
homepage: https://github.com/wstrange/asn1lib
environment:
 sdk: '>=2.2.0 <3.0.0'
dev_dependencies:
  test: '>= 1.5.3'
  convert: '^2.0.1'
  pedantic: ^1.9.0
