# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  validations_generator:
    import: "package:validations_generator/validations_generator.dart"
    builder_factories:
      - validatorGeneratorFactory
    build_extensions:
      .dart:
        - "validations.g.part"
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
