name: process_run
version: 0.10.12+3
description: Process run helpers for Linux/Win/Mac and which like feature for finding executables.
homepage: https://github.com/tekartik/process_run.dart

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  path: '>=1.6.1 <3.0.0'
  collection: '>=1.14.10 <3.0.0'
  io: '>=0.3.0 <2.0.0'
  yaml: '>=2.0.0 <4.0.0'
  meta: '>=1.1.0 <3.0.0'
  args: '>=1.5.0 <3.0.0'
  pub_semver: '>=1.4.0 <3.0.0'

dev_dependencies:
  pedantic: '>=1.4.0'
  test: '>=1.2.0'
  async: any
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
