name: flutter_screenutil
description: A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
version: 3.1.1
homepage: https://github.com/OpenFlutter/flutter_screenutil/tree/beta

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.19.0-4.3.pre"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
