name: flutter_rating_bar
description: A simple yet fully customizable ratingbar for flutter which also include a rating bar indicator, supporting any fraction of rating.
version: 1.3.0+1
author: Sarbagya Dhaubanjar <github@sarbagyastha.com.np>
homepage: https://github.com/sarbagyastha/flutter_rating_bar

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
