name: js
version: 0.6.3-nullsafety.2
description: Annotations to create static Dart interfaces for JavaScript APIs.
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/js

environment:
  sdk: '>=2.10.0-0 <2.12.0'

dev_dependencies:
  pedantic: ^1.9.0
