name: validations
description: Validations for dart models.
version: 0.8.5+1
homepage: https://github.com/dartlib/validations.git
author: Rob Halff <rob.halff@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  decimal: ^0.3.5
  meta: '>=1.0.0 <2.0.0'
  intl: '>=0.15.8 <1.0.0'
  validators: ^2.0.0

dev_dependencies:
  coverage: ^0.12.2
  build_runner:
  validations_generator: ^0.8.4
  pedantic: ^1.0.0
  test: ^1.0.0
  test_coverage: ^0.3.0
